venue:
    resource: "@VenueBundle/Controller/"
    type:     annotation
    prefix:   /

news:
    resource: "@NewsBundle/Controller/"
    type:     annotation
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
alogin:
    pattern: /alogin
    defaults: {_controller: VenueBundle:Admin:adminLog }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

    
