<?php

namespace Acme\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegRepository extends EntityRepository
{
}
